spring.application.name=moneyquest

spring.datasource.url=jdbc:mysql://localhost:3306/mqdb
spring.datasource.username=mquser
spring.datasource.password=Rezo_0000


spring.profiles.active=prod

# 30分に設定する場合（m = 分、s = 秒、h = 時間）
server.servlet.session.timeout=1h
